Feat/brave search
freedomgamesdev/wikigg-redirect-extension pull request #49
Opened 2024-01-06 22:47 UTC by ManagarmrWhisperer

Some cleaning and testing should be done, especially for hiding the results. The logic for running should be improved, since the page gets re-rendered two times it shouldn't be necessary to use a MO.

- [ ] Improve running logic
- [ ] Cleaning up the code
- [ ] Checking result hiding.

2024-01-09 16:04 UTC, alex4401 commented on js/baseSearch.js
> +    config = config || { attributes: false, childList: true, subtree: true };
I don't see much use in this helper other than possibly lowering efficiency.

2024-01-09 16:05 UTC, alex4401 commented on js/braveSearch.js
> +    makePlaceholderElement( wiki ) {
Should be extracted into a common module.

2024-01-09 16:06 UTC, alex4401 commented on js/braveSearch.js
> +    ENGINE_LAYOUT_SELECTOR: '#results',
These selectors should be moved into constants if shared with filter.

2024-01-09 16:06 UTC, alex4401 commented on js/braveSearch.js
> +        out.style.backgroundColor = document.querySelector( 'html.dark' )
document.documentElement.classList.has( 'dark' )

2024-01-09 16:07 UTC, alex4401 commented on js/braveSearch.js
> +            link.href = ( new URLSearchParams( link.href ) ).get( 'url' );
Are you sure this is what you want done here?

2024-01-09 16:08 UTC, alex4401 commented on js/braveSearch.js
> +            if ( /(?<=.+):\/\//.test( child.textContent ) ) {
Is this actually needed? What is it trying to solve exactly?

2024-01-09 16:08 UTC, alex4401 commented on js/braveSearch.js
> +            child.textContent = child.textContent.replace( new RegExp( `${wiki.oldId || wiki.id}.(fandom|gamepedia)?.com` ), `${wiki.id}.wiki.gg` );
Make the regexp a local constant.

2024-01-09 16:10 UTC, alex4401 commented on js/braveSearch.js
> +            element.prepend( this.makeBadgeElement( isTopLevel ) );
You're passing a closure to the function, and not a bool. This is not doing what you want it doing.

I don't see any reasons for the closure either.

2024-01-09 16:11 UTC, alex4401 commented on js/braveSearch.js
> +    rewriteURLElement( wiki, node ) {
`rewriteUrlElement`

2024-01-09 16:12 UTC, alex4401 commented on manifest_chrome.json
This file was wrongly moved into repository root.

2024-01-10 18:30 UTC, ManagarmrWhisperer commented on js/braveSearch.js
> +    makePlaceholderElement( wiki ) {
Should we move  `makeBadgeElement` too?

2024-01-10 20:07 UTC, ManagarmrWhisperer commented on js/braveSearch.js
> +            link.href = ( new URLSearchParams( link.href ) ).get( 'url' );
Yep, we need that check!

2024-01-11 15:56 UTC, alex4401 requested changes
Left first review comments.

2024-01-11 15:57 UTC, alex4401 commented on js/braveSearch.js
> +    makePlaceholderElement( wiki ) {
Yes.

2024-01-18 19:47 UTC, alex4401 requested changes

2024-01-18 19:47 UTC, alex4401 commented on js/braveSearch.js
> +        if ( linkElement.parentElement && document.querySelector( this.ENGINE_LAYOUT_SELECTOR ).contains( linkElement ) ) {
Write a comment what this is for.

2024-01-18 19:47 UTC, alex4401 commented on js/braveSearch.js
> +            oldElement.style.display = 'none';
Other modules remove the result container. Why hide here? This should be explained in the source.

2024-01-18 19:47 UTC, alex4401 commented on js/braveSearch.js
> +            oldElement.parentElement.prepend( makePlaceholderElement( wiki ), oldElement );
This will spawn placeholders at the top of the results container, won't it?

2024-01-18 19:47 UTC, alex4401 commented on js/braveSearch.js
> +                resultContainer.insertBefore( makePlaceholderElement( wiki ), oldElement );
Can't you access the results container via parentNode if oldElement is its child anyway?

2024-01-18 19:47 UTC, alex4401 commented on js/braveSearch.js
> +                    const resultContainer = document.querySelector( this.ENGINE_LAYOUT_SELECTOR );
You've already run this query before.

2024-01-18 19:47 UTC, alex4401 commented on js/braveSearch.js
> +observeElement( '#results', { attributes: false, childList: true, subtree: true }, runCallback );
A closure will be sufficient here, and cleaner.

2024-01-18 19:47 UTC, alex4401 commented on manifests/chrome_dev.json
> +
Redundant new line.

2024-01-18 19:48 UTC, alex4401 commented on js/baseSearch.js
> +        out.style.backgroundColor = document.documentElement.classList.has( 'dark' )
This is not generic.

2024-01-18 19:49 UTC, alex4401 commented on js/baseSearch.js
> +export function makeBadgeElement( isTopLevel ) {
Spacing.

2024-01-18 19:49 UTC, alex4401 commented on js/baseSearch.js
> +export function makePlaceholderElement( wiki ) {
Spacing

2024-01-18 19:49 UTC, alex4401 commented on js/baseSearch.js
> +    }
Indents.

2024-01-18 19:50 UTC, alex4401 commented on js/baseSearch.js
> +
Redundant new line. This method should also return the observer.

2024-01-18 19:51 UTC, alex4401 commented on js/braveSearch.js
> +                    continue;
Invert the if. The rewriteTitle call can happen if the condition is met, not if the negated condition is not met.

2024-01-20 12:15 UTC, alex4401 commented on rollup-config-background.mjs
> +    { script: 'search/ddg', output: 'ddg', isContentScript: true },
The DDG module got duplicated here.

2024-01-20 12:15 UTC, alex4401 commented on js/search/braveSearch.js
> +
Redundant new line.

2024-01-20 12:16 UTC, alex4401 requested changes
Rebase on top of feat/search2 and resolve remaining change comments.

2024-03-25 12:29 UTC, closed without merging